### PR TITLE
Created Profile and DonationHistory/Events screens

### PR DESCRIPTION
**Pull request by cwpenner**
User profile and donation history/my events can be accessed from the profile button. Static info to be replaced with database info

### CODE REVIEW

**Comment by dchachul** [comment]
when signing in as admin, clicking on profile and activity history the app throws an error and "hangs"

**Comment by cwpenner** [comment]
Fixed issue with My Activity Button

**Comment by dchachul** [comment]
all good now, can sign in and review profile and activity history

**Review by dchachul — APPROVED** [review]
Able to sign in and review Profile and My Activity screens.

**Pull request merged**
